[package]
name = "hello"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.3.1"

[profile.release]
# Optimize for small code size
opt-level = "s"
